-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 20:22:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema it_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema it_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `it_company` DEFAULT CHARACTER SET utf8 ;
USE `it_company` ;

-- -----------------------------------------------------
-- Table `it_company`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`companies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `field` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`work_record_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`work_record_books` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `start_date` TIMESTAMP NOT NULL,
  `end_date` TIMESTAMP NOT NULL,
  `companies_id` BIGINT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_work_record_books_companies1_idx` (`companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_record_books_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `it_company`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`countries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`addresses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `building` TINYINT NOT NULL,
  `appartment` TINYINT NOT NULL,
  `country_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_adresses_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_adresses_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `it_company`.`countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`offices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `area` DOUBLE NOT NULL,
  `adress_id` BIGINT NOT NULL,
  `companies_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_offices_adresses1_idx` (`adress_id` ASC) VISIBLE,
  INDEX `fk_offices_companies1_idx` (`companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_offices_adresses1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `it_company`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `it_company`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`departments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `offices_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_departments_offices1_idx` (`offices_id` ASC) VISIBLE,
  CONSTRAINT `fk_departments_offices1`
    FOREIGN KEY (`offices_id`)
    REFERENCES `it_company`.`offices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`salaries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`positions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salaries_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_positions_salaries1_idx` (`salaries_id` ASC) VISIBLE,
  CONSTRAINT `fk_positions_salaries1`
    FOREIGN KEY (`salaries_id`)
    REFERENCES `it_company`.`salaries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`passes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`passes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`employees` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `work_record_book_id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `position_id` BIGINT NOT NULL,
  `passes_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_employees_work_record_books1_idx` (`work_record_book_id` ASC) VISIBLE,
  INDEX `fk_employees_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_employees_positions1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_employees_passes1_idx` (`passes_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_work_record_books1`
    FOREIGN KEY (`work_record_book_id`)
    REFERENCES `it_company`.`work_record_books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `it_company`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `it_company`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_passes1`
    FOREIGN KEY (`passes_id`)
    REFERENCES `it_company`.`passes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`devices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `os` VARCHAR(45) NOT NULL,
  `employees_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_laptops_employees1_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_laptops_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `it_company`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`projects` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`offers` (
  `employees_id` BIGINT NOT NULL,
  `projects_id` BIGINT NOT NULL,
  PRIMARY KEY (`employees_id`, `projects_id`),
  INDEX `fk_employees_has_projects_projects1_idx` (`projects_id` ASC) VISIBLE,
  INDEX `fk_employees_has_projects_employees_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_has_projects_employees`
    FOREIGN KEY (`employees_id`)
    REFERENCES `it_company`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `it_company`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it_company`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_company`.`credentials` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `employees_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_credentials_employees1_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_credentials_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `it_company`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
